# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- '*'

variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    tag: 'latest'
  ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
    tag: $(Build.SourceBranchName)

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub connection'
        repository: 'hoppel/rust_mapgen'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'